### ISSUE TITLE
only id supported?

### ISSUE THREAD

**Issue by gobbedy** [mattpodolak/pmaw#1]
Looks great!

From the readme, am I to understand that the ```search_submissions``` method only supports the ```ids``` parameter?

**Comment by mattpodolak** [comment]
Hi @gobbedy , currently only the `ids` parameter is supported for `search_submissions`. 

v0.1.0 is being released this week which will include the full functionality for this method

**Comment by gobbedy** [comment]
@mattpodolak that's awesome! then i may be your first user for v0.1.0

**Comment by mattpodolak** [comment]
Hi @gobbedy, I'm closing this ticket as `v0.1.0` was released today which includes non-id based search for comments and submissions. Please open another ticket if you have any issues or feature requests.
