### ISSUE TITLE
Is there a way to turn off log response?

### ISSUE THREAD

**Issue by turmeric-blend** [mattpodolak/pmaw#11]
Hi, is there a way to turn off the log response?

> I0317 17:36:13.663935 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2852
I0317 17:36:14.613399 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2771
I0317 17:36:16.100443 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2700
I0317 17:36:16.821416 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2626
I0317 17:36:17.709720 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2555
I0317 17:36:19.522857 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2495
I0317 17:36:20.668120 139656604510016 PushshiftAPIBase.py:141] Remaining limit 2439

**Comment by mattpodolak** [comment]
Hi @turmeric-blend, why do you need to remove to suppress the info logs? 

I may consider moving some of these to the DEBUG level.

**Comment by turmeric-blend** [comment]
For me I do have other logs that I want to see so this particular one pushes my other logs out of the terminal which is not ideal. Maybe it would be nice to have an option for this. Thanks!

**Comment by mattpodolak** [comment]
Reduced unnecessary `INFO` and `DEBUG` logging in `v1.0.5`
