### ISSUE TITLE
fields parameter

### ISSUE THREAD

**Issue by itang1** [mattpodolak/pmaw#16]
Hi. I'm drawing blank datasets when I try to use the `fields` param to filter for specific fields (in order to reduce bandwidth).

This is what I want to do:
`comments = api.search_comments(subreddit=subreddit, limit=100, before=before, after=after, sort_type="score", fields="body,score,author,created_utc")`

This feature is supposed to be supported by Pushshift ([Pushshift: Using the fields parameter](https://github.com/pushshift/api#using-the-fields-parameter)). However, when I use the PMAW wrapper to do this, it returns me a blank object.

The PMAW wrapper appears to work fine for filtering exactly one field (e.g. `fields="body"`). Is it possible to filter for more fields with this wrapper?

**Comment by mattpodolak** [comment]
Hi @itang1 `pmaw` supports a single field such as `fields="body"` or a list of strings such as `fields=["body","score","author","created_utc"]`
