### ISSUE TITLE
Score parameters

### ISSUE THREAD

**Issue by Hastte** [mattpodolak/pmaw#20]
Hello
When i try  `api.search_submissions(subreddit="science", limit=None, score>=1000`
I get an error` SyntaxError: positional argument follows keyword argument`
Do you know how to fix it ?
Thanks

**Comment by mattpodolak** [comment]
Hi @Hastte, can you try the following: `api.search_submissions(subreddit="science", limit=None, score=">1000")`

**Comment by Hastte** [comment]
Yes that's kinda work buuut, i get less result than usual using pushshift api directly

**Comment by mattpodolak** [comment]
Can you share your queries?

I tested the score parameter and got the results I expected, using Pushshift directly we can see 16 results exist (https://api.pushshift.io/reddit/search/submission/?q=dodo%20bird&metadata=true&score=%3E1000). 
```json
        "execution_time_milliseconds": 98.48,
        "index": "rs",
        "metadata": "true",
        "q": "dodo bird",
        "ranges": [],
        "results_returned": 16,
        "score": [
            ">1000"
        ],
        "shards": {
            "failed": 0,
            "skipped": 0,
            "successful": 24,
            "total": 24
        },
        "size": 25,
        "sort": "desc",
        "sort_type": "created_utc",
        "timed_out": false,
        "total_results": 16
```

Using the same query, re-written in pmaw, we get 16 results: 
```python
posts = api.search_submissions(q="dodo bird", score=">1000") # reports 16 available results
len(posts) # 16
```

**Comment by Hastte** [comment]
![image](https://user-images.githubusercontent.com/41826976/120903638-a77e9300-c647-11eb-8651-98688a841d7a.png)
![image](https://user-images.githubusercontent.com/41826976/120903681-d563d780-c647-11eb-9d59-166b4b0f02ee.png)
![image](https://user-images.githubusercontent.com/41826976/120903693-ea406b00-c647-11eb-9930-95e42e1572ce.png)

And now it's the opposite

**Comment by mattpodolak** [comment]
Your score parameter for Pushshift is malformed, "score>20000" should be "score=>20000".

This is the correct query: https://api.pushshift.io/reddit/search/submission/?subreddit=science&metadata=true&score=%3E20000

It has the same number of results as pmaw so I will be closing this issue.
