### ISSUE TITLE
** new to github/programming (so might be a dumb question)** Module is pulling multiple duplicates for each Submission  

### ISSUE THREAD

**Issue by nnnnnnn1** [mattpodolak/pmaw#22]
Again, not sure how to ask a question....but I have been using the 'search_submissions' class and it is pulling multiple duplicates for each submission. Is there something I am doing wrong?

**Comment by mattpodolak** [comment]
Hi, can you please provide the code you are running, pmaw version, the log output / result, and the expected output/result?
