### ISSUE TITLE
Successful Rate 0% no matter what

### ISSUE THREAD

**Issue by eryk-mazus** [mattpodolak/pmaw#36]
Hi,

I found a strange issue, similar to [#23](https://github.com/mattpodolak/pmaw/issues/23).  Basically, now matter what I do I get 0% Successful Rate when trying to fetch comments by their ids. I tried to pass the ids as list and as a joint string with ids delimited by  `,`.

Below is the reproducible example with sample of ids that I want to fetch:

```
import time
from pmaw import PushshiftAPI

api = PushshiftAPI()

if __name__ == "__main__":
    # list of comments
    comment_ids = ['czyja5h', 'czyjfsw', 'czyjhfs', 'czyjhqz', 'czyjufm', 'czyk71o', 'czykgjk', 'czykuef', 'czyl1me', 'czylher']

    # fetch the body of comments
    t = time.time()

    comments = api.search_comments(ids=comment_ids)
    comment_list = [comment for comment in comments]

    print(f"Fetching {len(comment_list)} comments complete, it took {time.time() - t:.3f}s")
    print('...')
```

**Comment by mattpodolak** [comment]
thanks for reporting this issue! i'll take a look

**Comment by Randcd415** [comment]
I'm experiencing this as well.

**Comment by mattpodolak** [comment]
It looks like theres currently an issue with the id search on Pushshift, the [example comments id search query](https://api.pushshift.io/reddit/comment/search?ids=dlrezc8,dlrawgw,dlrhbkq) provided in the Pushshift API documentation returns an Internal Server Error
