### ISSUE TITLE
Confusion about multithreading

### ISSUE THREAD

**Issue by kadnan** [mattpodolak/pmaw#47]
Hi

When I call :

```
from psaw import PushshiftAPI as psawAPI
from pmaw import PushshiftAPI as pmawAPI
```

```
api = psawAPI()
api_request_generator = list(api.search_submissions(...)
```

And
```
api = pmawAPI()
api_request_generator = list(api.search_submissions(...)
```

How it makes `search_submissions` mutithreaded? ain't both psaw and pmsaw making a single REST call to PushShift?

**Comment by mattpodolak** [comment]
hey @kadnan, `search_submissions` is multithreaded by splitting up a request into many smaller requests that are divided across multiple threads. You can see where that happens [here](https://github.com/mattpodolak/pmaw/blob/master/pmaw/PushshiftAPIBase.py#L261-L269)
