### ISSUE TITLE
Changed format in parent_id

### ISSUE THREAD

**Issue by kama-brown** [mattpodolak/pmaw#55]
Hello Matt, Thank you for your hardwork. 
I just found out that the data format of the column parent_id changed from post id, such as t3_zyw8x9, to an int , like 41497293111.

Is it still the correct parent_id? If yes, do we have a way to convert it back to the traditional post_id format?

**Comment by mattpodolak** [comment]
I believe the column you are looking for is `link_id`

**Comment by kama-brown** [comment]
Dear Matt,
The link_id column has no problem, I am talking about the parent_id column, which is the column containing the link_id of the parent comment that the comment is responding to. By comparing link_id and parent_id, I can reconstruct the whole discussion. When I used your package a month ago, the parent_id was formatted as the link_id. But this time the parent_id is an integer.
Sorry if I did not express my question clearly. English is not my first language.
