### ISSUE TITLE
I'd recommend to use parquet partitions

### ISSUE THREAD

**Issue by veonua** [mattpodolak/pmaw#6]
it gives the smaller size and faster save\load time, while supported by the majority of data libraries

**Comment by veonua** [comment]
wallstreetbets_posts.csv > 920Mb
wallstreetbets_posts.parquet ~ 120Mb

**Comment by mattpodolak** [comment]
Hi @veonua, thanks for pointing this out. However, this is not functionality of the `pmaw` library, but post-processing done after responses have been retrieved with `pmaw` so I will be closing this issue. 

The documentation will continue to provide an example using  `.csv`, as this benefits the largest number of users.

**Comment by veonua** [comment]
the proposal was for a cache as well

**Comment by mattpodolak** [comment]
ah okay, sorry, that wasn't clear. I know it takes up less space than `.pickle` which is currently being used, but I haven't done any benchmarks with it yet.
