### ISSUE TITLE
If pushshift fails to return data, can crash trying to warn about it

### ISSUE THREAD

**Issue by ninjainventor** [mattpodolak/pmaw#8]
in gen_url_payloads

  all_ids = self.payload['ids']
                if len(all_ids) == 0 and self.limit > 0:
                    warnings.warn(
                        f'{self.limit} items were not found in Pushshift')
                self.limit = len(all_ids)

TypeError: '>' not supported between instances of 'NoneType' and 'int'

So seemingly limit is None type. Or I've made a mistake somehow. But I think my code is working because this only crashes intermittently (meaning it is consistent with what I would expect if Pushshift was occassionally failing).

**Comment by mattpodolak** [comment]
I'll look into this, but this makes sense.

Can you share the query you are running as well?

**Comment by ninjainventor** [comment]
submissions = api.search_submissions(
        subreddit="wallstreetbets", limit=desiredLimit, before=beforeDate, after=afterDate, mem_safe=True)
    allOfSubmissions = [post for post in submissions]
    sub_ids = [post["id"] for post in allOfSubmissions]
    pprint.pprint(allOfSubmissions)
    sub_df = pd.DataFrame(allOfSubmissions)

    sub_df.to_csv('./'+inputSubreddit+'Submissions.csv', header=True,
                  index=False, columns=list(sub_df.axes[1]))

    # Comments

    # There are two main ways to approach building a comments dataset. First, we can directly use the search_comments endpoint and return comments based on this search or we can return all comments for a set of submissions.

    # Approach 1

    # In this approach we directly search for comments

    # Approach 2

    # In this approach, we create a dataset of comments based on the submissions we have already retrieved.

    #subs_df = pd.read_csv('./'+inputSubreddit+'Submissions.csv', header=0)

    #sub_ids = list(subs_df.loc[:, 'id'])
    print(sub_ids)
    print("we have read SUBS. On to comments")

    # retrieve comment ids for submissions
    comment_ids = api.search_submission_comment_ids(ids=sub_ids)


    # retrieve comments by id

    comment_id_list = [c_id for c_id in comment_ids]
    print("\nHere are comment ID lists\n")
    pprint.pprint(comment_id_list)

    comments = api.search_comments(ids=comment_id_list, mem_safe=True)

    comments_df = pd.DataFrame(comments)

    comments_df.to_csv('./'+inputSubreddit+'_comments.csv',
                       header=True, index=False, columns=list(comments_df.axes[1]))

Has some debug statements. Found it would run inconsistently. I.e. one time ran all the way through, other time crashed with the TypeError I mentioned.

**Comment by mattpodolak** [comment]
Closed this issue, as a fix was released for this in `v1.0.4`. Please open another issue if another problem arises
